name: Actions
on:
  pull_request: {}
  push: { branches: [main]}

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
   name: Build Project
   runs-on: ubuntu-latest
   steps:
     #Checkout
     - name: Checkout
       uses: actions/checkout@v2
       with:
         lfs: true
     
     #Cache
     - uses: actions/cache@v1.1.0
       with:
         path: Library
         key: Library
     
     #Run Tests
     - name: Run Tests
       uses: webbertakken/unity-test-runner@v1.3
       with:
         unityVersion: 2019.4.14f1
     
     #Build
     - name: Build
       uses: webbertakken/unity-builder@v0.10
       with:
         unityVersion: 2019.4.14f1
         targetPlatform: WebGL
     
     #Output
     - uses: actions/upload-artifact@v1
       with:
         name: Build
         path: build
